### ISSUE TITLE
Setting Up Models

### ISSUE THREAD

**Issue by vhall98** [hsgubert/cassandra_migrations#65]
After successfully working through various bugs and forced to use jruby in order for cassandra_migrations to work, I noticed when running "rake cassandra:setup/create/migrate, no model is created.  Nothing in documentation refers to setting up models either.  Can you advise on how to incorporate models with cassandra_migration?

**Comment by bsbodden** [comment]
@vhall98 I'm using cassandra_migration with Ruby 2.x for a while now I don't know why you are being force to use jruby? In terms of the models, cassandra_migrations is not an ORM (or a ONRM - Object Non-Relational Mapper). For an ORM I've used https://github.com/cequel/cequel in the past or have built my own, but in general you might not really need one, since the data structures are fairly simple and there are no joins.

**Comment by vhall98** [comment]
Hi Brian, I wasn't implying I had issues with cassandra_migration, it was my local windows environment  and when I switched to jruby, no more issues.  I like cassandra_migration but was under false self impression that it could do models.  Thanks for quick response.

**Comment by bsbodden** [comment]
In the past I've made my Cassandra models implement ActiveModel to provide some basic functionality to make working with Rails easier but not much more beyond that. Let us know if you find any issues working with JRuby. Thanks!
